### ISSUE TITLE
`this` is not correct

### ISSUE THREAD

**Issue by develar** [zertosh/babel-plugin-transform-inline-imports-commonjs#8]
```js
import { lookup as lookupMime } from "mime"

lookupMime("foo.icns")
```

Generated code: `(0, (_mime || _load_mime()).lookup)(fileName)`

Error: 
```js
TypeError: Cannot read property 'icns' of undefined
    at Mime.lookup (/Users/develar/Documents/electron-builder/node_modules/mime/mime.js:72:20)
    at eval (eval at evaluate (unknown source), <anonymous>:1:36)
    at Mime.lookup (/Users/develar/Documents/electron-builder/node_modules/mime/mime.js:72:3)
```

Because `this` is not `Mime` but file. 

Correct code must be: `(_mime || _load_mime()).lookup(fileName)`

Why `path.replaceWith(t.sequenceExpression([t.numericLiteral(0), remap]));` is required?

**Comment by zertosh** [comment]
I believe the behavior you're getting is consistent with how imports work. Babel transpiles to equivalent code: http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&experimental=true&loose=false&spec=false&code=import%20%7B%20lookup%20as%20lookupMime%20%7D%20from%20%22mime%22%0A%0AlookupMime(%22foo.icns%22)%0A

From `mime`'s [code](https://github.com/broofa/node-mime/blob/a5c1455742075c8a530a1300a6e0bce94be2cdc6/mime.js#L69-L73), the module's export is an instance of `Mime` and `lookup` depends on the instance.

**Comment by develar** [comment]
@zertosh Thanks, I got your point. Indeed — it is not number of static methods — it is default export of Mime object instance. Thanks for explanation. My import must be `import Mime from "mime"` 

Could you please explain in any case why `(0,` is required? It seems it is not necessary.

**Comment by zertosh** [comment]
It's [a cheap way](http://www.2ality.com/2015/12/references.html) to ensure that the `this` is correct for the given mode (`global` or `undefined`), in order to be spec compliant. See http://stackoverflow.com/questions/32275135/why-does-babel-rewrite-imported-function-call-to-0-fn
